name: memory
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  mime: ^1.0.4
  path_provider: ^2.1.1
  flutter_tts: ^4.2.3
  intl: ^0.20.2
  speech_to_text: 7.1.0
  permission_handler: 12.0.0+1
  http: 1.4.0
  table_calendar: ^3.2.0
  calendar_view: ^1.4.0 
  syncfusion_flutter_calendar: ^30.1.38
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  record: ^6.0.0
  just_audio: ^0.10.4
  universal_html: ^2.2.4
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  uuid: ^4.5.1
  firebase_storage: ^12.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/image/default_avatar.png
